<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Miscellaneous</name>
   <tag></tag>
   <elementGuidId>9c192bfd-4eba-4e19-968c-a16dc1f51678</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Miscellaneous</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bcomserver&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-4&quot;]/a[1]/div[@class=&quot;adminTMPS&quot;]/h3[1]/a[1]</value>
   </webElementProperties>
</WebElementEntity>
