<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Servers</name>
   <tag></tag>
   <elementGuidId>3e96f7fa-46e2-45ca-845a-539c76c1fe90</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Servers</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/c3-app[1]/ng-component[1]/div[@class=&quot;ui-content&quot;]/div[@class=&quot;container&quot;]/c3-adm-home[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-5&quot;]/div[@class=&quot;admin-r21&quot;]/div[@class=&quot;d-flex&quot;]/div[@class=&quot;item&quot;]/a[@class=&quot;ad-home-hilight&quot;]/div[@class=&quot;ad-devices&quot;]/span[1]</value>
   </webElementProperties>
</WebElementEntity>
