<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_img-wrp</name>
   <tag></tag>
   <elementGuidId>0c4eb53d-2310-468f-aa6a-b1204ef3565f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;expand&quot;)/c3-case-permissions[1]/div[@class=&quot;widget&quot;]/h4[1]/a[@class=&quot;ui-acc&quot;]/img[@class=&quot;img-wrp&quot;][count(. | //img[@class = 'img-wrp']) = count(//img[@class = 'img-wrp'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-wrp</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>assets/images/icons/expand.png</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;expand&quot;)/c3-case-permissions[1]/div[@class=&quot;widget&quot;]/h4[1]/a[@class=&quot;ui-acc&quot;]/img[@class=&quot;img-wrp&quot;]</value>
   </webElementProperties>
</WebElementEntity>
