<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h3_StatesProvinces</name>
   <tag></tag>
   <elementGuidId>48491a77-2f77-4093-9011-1c9928162131</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>States/Provinces</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;infrastructure-home&quot;)/c3-misc-home[1]/div[@class=&quot;templates TMPpre-template&quot;]/div[@class=&quot;perwrp TMPpre perwrp-template&quot;]/div[@class=&quot;adminTMP adminGrid&quot;]/ul[1]/li[@class=&quot;uiAD-cn&quot;]/a[1]/div[@class=&quot;adminTMPS&quot;]/h3[1]</value>
   </webElementProperties>
</WebElementEntity>
