<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>courier_table</name>
   <tag></tag>
   <elementGuidId>99387e1b-e5b8-44fc-bb97-e3b164c1fc2e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;courier-table&quot;]/table/tbody/tr[2]/td/table</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;courier-table&quot;]/table/tbody/tr[2]/td/table</value>
   </webElementProperties>
</WebElementEntity>
