<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_expbtn</name>
   <tag></tag>
   <elementGuidId>00edeb6b-214b-41ea-a366-e6f120ed918d</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>expbtn</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Export CSV</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/c3-app[1]/ng-component[1]/div[@class=&quot;ui-content&quot;]/div[@class=&quot;container&quot;]/c3-navigator[1]/div[@class=&quot;single-video&quot;]/c3-shared-evidence[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12&quot;]/div[@class=&quot;recent-uploaded shared-evidences ui-mobile ui-nvs&quot;]/div[@class=&quot;cr-wrps&quot;]/div[@class=&quot;right-wrps&quot;]/input[@class=&quot;expbtn&quot;]</value>
   </webElementProperties>
</WebElementEntity>
