<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_selectall</name>
   <tag></tag>
   <elementGuidId>10b33bf2-5011-496b-afa0-ebe59a70ace9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@class = 'selectall' and @type = 'checkbox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectall</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shared-evidence&quot;)/div[@class=&quot;&quot;]/div[@class=&quot;case-table casefile uix-list case-ui-alter case-table-audit-log&quot;]/table[1]/thead[1]/tr[1]/th[@class=&quot;check&quot;]/div[@class=&quot;uiall&quot;]/em[@class=&quot;checknew&quot;]/input[@class=&quot;selectall&quot;]</value>
   </webElementProperties>
</WebElementEntity>
